In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("olist_customers_dataset.csv")

print("Dataset Shape:", df.shape)

Dataset Shape: (99441, 5)

In [2]:
display(df.head())

print("Column Names:")
print(df.columns.tolist())

print("\nData Types:")
print(df.dtypes)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:", df.duplicated().sum())

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

Column Names:
['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']

Data Types:
customer_id                   str
customer_unique_id            str
customer_zip_code_prefix    int64
customer_city                 str
customer_state                str
dtype: object

Missing Values:
customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

Duplicate Rows: 0

In [3]:
print("Unique customer_id:", df["customer_id"].nunique())
print("Unique customer_unique_id:", df["customer_unique_id"].nunique())
print("Unique cities:", df["customer_city"].nunique())
print("Unique states:", df["customer_state"].nunique())

Unique customer_id: 99441
Unique customer_unique_id: 96096
Unique cities: 4119
Unique states: 27

In [4]:
df["customer_zip_code_prefix"] = (
    df["customer_zip_code_prefix"]
    .astype(str)
    .str.zfill(5)
)

print("ZIP Code Data Type:", df["customer_zip_code_prefix"].dtype)
print("\nSample ZIP Codes:")
print(df["customer_zip_code_prefix"].head())

ZIP Code Data Type: str

Sample ZIP Codes:
0    14409
1    09790
2    01151
3    08775
4    13056
Name: customer_zip_code_prefix, dtype: str

In [5]:
zip_length = df["customer_zip_code_prefix"].str.len()

print("ZIP codes with invalid length:",
      (zip_length != 5).sum())

print("ZIP codes with non-numeric values:",
      (~df["customer_zip_code_prefix"].str.isnumeric()).sum())

ZIP codes with invalid length: 0
ZIP codes with non-numeric values: 0

In [6]:
print("City values with leading/trailing spaces:",
      (df["customer_city"] != df["customer_city"].str.strip()).sum())

print("State values with leading/trailing spaces:",
      (df["customer_state"] != df["customer_state"].str.strip()).sum())

City values with leading/trailing spaces: 0
State values with leading/trailing spaces: 0

In [7]:
print("Empty city values:",
      (df["customer_city"].str.strip() == "").sum())

print("Empty state values:",
      (df["customer_state"].str.strip() == "").sum())

Empty city values: 0
Empty state values: 0

In [8]:
cleaned_df = df.copy()

# Remove duplicate records
cleaned_df = cleaned_df.drop_duplicates()

# Standardize text values
cleaned_df["customer_city"] = (
    cleaned_df["customer_city"]
    .str.strip()
    .str.lower()
)

cleaned_df["customer_state"] = (
    cleaned_df["customer_state"]
    .str.strip()
    .str.upper()
)

print("Original records:", len(df))
print("Cleaned records:", len(cleaned_df))

print("Remaining missing values:",
      cleaned_df.isnull().sum().sum())

print("Remaining duplicates:",
      cleaned_df.duplicated().sum())

Original records: 99441
Cleaned records: 99441
Remaining missing values: 0
Remaining duplicates: 0

In [9]:
quality_report = pd.DataFrame({
    "Check": [
        "Total Records",
        "Total Columns",
        "Missing Values",
        "Duplicate Records",
        "Invalid ZIP Length",
        "Non-Numeric ZIP Values",
        "Empty City Values",
        "Empty State Values"
    ],
    "Result": [
        len(df),
        len(df.columns),
        df.isnull().sum().sum(),
        df.duplicated().sum(),
        (df["customer_zip_code_prefix"].str.len() != 5).sum(),
        (~df["customer_zip_code_prefix"].str.isnumeric()).sum(),
        (df["customer_city"].str.strip() == "").sum(),
        (df["customer_state"].str.strip() == "").sum()
    ]
})

display(quality_report)

                    Check  Result
0           Total Records   99441
1           Total Columns       5
2          Missing Values       0
3       Duplicate Records       0
4      Invalid ZIP Length       0
5  Non-Numeric ZIP Values       0
6       Empty City Values       0
7      Empty State Values       0

In [10]:
cleaned_df.to_csv(
    "cleaned_olist_customers.csv",
    index=False
)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [11]:
final_df = pd.read_csv(
    "cleaned_olist_customers.csv",
    dtype={"customer_zip_code_prefix": str}
)

print("Final Dataset Shape:", final_df.shape)

print("\nMissing Values:")
print(final_df.isnull().sum().sum())

print("\nDuplicate Rows:")
print(final_df.duplicated().sum())

print("\nData Types:")
print(final_df.dtypes)

print("\nFirst 5 Records:")
display(final_df.head())

Final Dataset Shape: (99441, 5)

Missing Values:
0

Duplicate Rows:
0

Data Types:
customer_id                 str
customer_unique_id          str
customer_zip_code_prefix    str
customer_city               str
customer_state              str
dtype: object

First 5 Records:

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,09790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,01151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,08775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP